//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionServicePrivateWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionServicePrivateWeb.HelpText", typeof(HelpText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this application which is set to the Azure Resource Group name..
        /// </summary>
        internal static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationInsightsInstrumentationKey.
        /// </summary>
        internal static string ApplicationInsightsInstrumentationKey {
            get {
                return ResourceManager.GetString("ApplicationInsightsInstrumentationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAEvalName.
        /// </summary>
        internal static string ASAEvalName {
            get {
                return ResourceManager.GetString("ASAEvalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAJoinName.
        /// </summary>
        internal static string ASAJoinName {
            get {
                return ResourceManager.GetString("ASAJoinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureResourceGroupName.
        /// </summary>
        internal static string AzureResourceGroupName {
            get {
                return ResourceManager.GetString("AzureResourceGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureStorageConnectionString.
        /// </summary>
        internal static string AzureStorageConnectionString {
            get {
                return ResourceManager.GetString("AzureStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Azure Subscription Id used for this deployment..
        /// </summary>
        internal static string AzureSubscriptionId {
            get {
                return ResourceManager.GetString("AzureSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureSubscriptionName.
        /// </summary>
        internal static string AzureSubscriptionName {
            get {
                return ResourceManager.GetString("AzureSubscriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the decision uses regular features or action-dependent features..
        /// </summary>
        internal static string DecisionType {
            get {
                return ResourceManager.GetString("DecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventHubInteractionConnectionString.
        /// </summary>
        internal static string EventHubInteractionConnectionString {
            get {
                return ResourceManager.GetString("EventHubInteractionConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventHubObservationConnectionString.
        /// </summary>
        internal static string EventHubObservationConnectionString {
            get {
                return ResourceManager.GetString("EventHubObservationConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExperimentalUnitDuration.
        /// </summary>
        internal static string ExperimentalUnitDuration {
            get {
                return ResourceManager.GetString("ExperimentalUnitDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExplorationEnabled.
        /// </summary>
        internal static string IsExplorationEnabled {
            get {
                return ResourceManager.GetString("IsExplorationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelIdList.
        /// </summary>
        internal static string ModelIdList {
            get {
                return ResourceManager.GetString("ModelIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumActions.
        /// </summary>
        internal static string NumActions {
            get {
                return ResourceManager.GetString("NumActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlineTrainerName.
        /// </summary>
        internal static string OnlineTrainerName {
            get {
                return ResourceManager.GetString("OnlineTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedModelId.
        /// </summary>
        internal static string SelectedModelId {
            get {
                return ResourceManager.GetString("SelectedModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsBlobUri.
        /// </summary>
        internal static string SettingsBlobUri {
            get {
                return ResourceManager.GetString("SettingsBlobUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainArguments.
        /// </summary>
        internal static string TrainArguments {
            get {
                return ResourceManager.GetString("TrainArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainFrequency.
        /// </summary>
        internal static string TrainFrequency {
            get {
                return ResourceManager.GetString("TrainFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApiName.
        /// </summary>
        internal static string WebApiName {
            get {
                return ResourceManager.GetString("WebApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebManageName.
        /// </summary>
        internal static string WebManageName {
            get {
                return ResourceManager.GetString("WebManageName", resourceCulture);
            }
        }
    }
}
