//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionServicePrivateWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionServicePrivateWeb.HelpText", typeof(HelpText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id ::: The name of this application which is set to the Azure Resource Group name..
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Insights Instrumentation Key ::: ApplicationInsightsInstrumentationKey.
        /// </summary>
        public static string ApplicationInsightsInstrumentationKey {
            get {
                return ResourceManager.GetString("ApplicationInsightsInstrumentationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Stream Analytics Policy Evaluation ::: ASAEvalName.
        /// </summary>
        public static string ASAEvalName {
            get {
                return ResourceManager.GetString("ASAEvalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Stream Analytics Join Server ::: ASAJoinName.
        /// </summary>
        public static string ASAJoinName {
            get {
                return ResourceManager.GetString("ASAJoinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Resource Group ::: AzureResourceGroupName.
        /// </summary>
        public static string AzureResourceGroupName {
            get {
                return ResourceManager.GetString("AzureResourceGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Storage Connection String ::: AzureStorageConnectionString.
        /// </summary>
        public static string AzureStorageConnectionString {
            get {
                return ResourceManager.GetString("AzureStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Subscription Id ::: The Azure Subscription Id used for this deployment..
        /// </summary>
        public static string AzureSubscriptionId {
            get {
                return ResourceManager.GetString("AzureSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Type ::: Whether the decision uses regular features or action-dependent features..
        /// </summary>
        public static string DecisionType {
            get {
                return ResourceManager.GetString("DecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub Interaction Connection String ::: EventHubInteractionConnectionString.
        /// </summary>
        public static string EventHubInteractionConnectionString {
            get {
                return ResourceManager.GetString("EventHubInteractionConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub Observation Connection String ::: EventHubObservationConnectionString.
        /// </summary>
        public static string EventHubObservationConnectionString {
            get {
                return ResourceManager.GetString("EventHubObservationConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Timeout (in seconds) ::: ExperimentalUnitDuration.
        /// </summary>
        public static string ExperimentalUnitDuration {
            get {
                return ResourceManager.GetString("ExperimentalUnitDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Exploration ::: IsExplorationEnabled.
        /// </summary>
        public static string IsExplorationEnabled {
            get {
                return ResourceManager.GetString("IsExplorationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Actions ::: NumActions.
        /// </summary>
        public static string NumActions {
            get {
                return ResourceManager.GetString("NumActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Trainer ::: OnlineTrainerName.
        /// </summary>
        public static string OnlineTrainerName {
            get {
                return ResourceManager.GetString("OnlineTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trained Models ::: SelectedModelId.
        /// </summary>
        public static string SelectedModelId {
            get {
                return ResourceManager.GetString("SelectedModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Blob Address ::: SettingsBlobUri.
        /// </summary>
        public static string SettingsBlobUri {
            get {
                return ResourceManager.GetString("SettingsBlobUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VW Training Arguments ::: TrainArguments.
        /// </summary>
        public static string TrainArguments {
            get {
                return ResourceManager.GetString("TrainArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Frequency ::: TrainFrequency.
        /// </summary>
        public static string TrainFrequency {
            get {
                return ResourceManager.GetString("TrainFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Endpoint ::: WebApiName.
        /// </summary>
        public static string WebApiAddress {
            get {
                return ResourceManager.GetString("WebApiAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Center Address ::: WebManageName.
        /// </summary>
        public static string WebManageName {
            get {
                return ResourceManager.GetString("WebManageName", resourceCulture);
            }
        }
    }
}
