//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Microsoft.Research.MultiWorldTesting.Contract")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corp")]
[assembly: System.Reflection.AssemblyProduct("Microsoft.Research.MultiWorldTesting.Contract")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) Microsoft Corp 2014-2016")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.Guid("d9d80c55-19ce-48fa-a2ef-7eae466b1f9b")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.2")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.2")]


