//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Microsoft.Research.MultiWorldTesting.ClientLibrary")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corp")]
[assembly: System.Reflection.AssemblyProduct("Microsoft.Research.MultiWorldTesting.ClientLibrary")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) Microsoft Corp 2014-2016")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("a991c863-165c-4fd5-b388-45b13df358a8")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.3")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.3")]


