//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Microsoft.Research.MultiWorldTesting.JoinUploader")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corp")]
[assembly: System.Reflection.AssemblyProduct("Microsoft.Research.MultiWorldTesting.JoinUploader")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) Microsoft Corp 2014-2016")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.Guid("324bd225-38a8-476f-bc96-ad563697274d")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.3")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.3")]


